ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-dev.neelimadevops.online
CATALOGUE_HOST: catalogue-dev.neelimadevops.online
REDIS_HOST: redis-dev.neelimadevops.online
USER_HOST: user-dev.neelimadevops.online
MYSQL_HOST: mysql-dev.neelimadevops.online
CART_HOST: cart-dev.neelimadevops.online
SHIPPING_HOST: shipping-dev.neelimadevops.online
RABBITMQ_HOST: rabbitmq-dev.neelimadevops.online
PAYMENT_HOST: payment-dev.neelimadevops.online
FRONTEND_HOST: frontend-dev.neelimadevops.online