- name: inclue app setup 
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yml 

- name: inclue app setup 
  ansible.builtin.import_role:
    name: common
    tasks_from: java-setup.yml    

- name: inclue app setup 
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yml  

- name: install dependencies
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - cryptography
  - PyMySQL

- name: start shipping
  ansible.builtin.service:
      name: shipping
      state: started

- name: load the products
    ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
    when: shipping_output.stdout  | int < 0

- name : import shipping data
  community.mysql.mysql_db:
    state: import
    name: all
    login_host: "{{ MYSQL_HOST }}"
    login_user: root
    login_password: Roboshop@1
    target: "{{item}}"
  loop:
  - /app/db/schema.sql
  - /app/db/app-user.sql
  - /app/db/master-data.sql

- name: restart shipping
  ansible.builtin.service:
    name: shipping
    state: restarted