#import role in ansible 
- name: inclue app setup 
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yml  

- name: include nodejs setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs-setup.yml 
# load catalogue role
#ansible finds meta dir and main.yml
# it depends on common role
# ansible executes main.yml in common /tasks folder
# now ansible starts executing tasks in 

- name: include nodejs setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yml 

- name: copy mongo repo
  ansible.builtin.template:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: check products loaded
  ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("cart")'
  register: cart_output

- name: print the output
  ansible.builtin.debug:
    msg: "{{ cart_output }}"

- name: load the products
  ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
  when: cart_output.stdout  | int < 0  



- name: start cart
  ansible.builtin.service:
    name: cart
    state: restarted
    enabled: yes